name: deploy

on:
  push:
    branches:
      - master

jobs:
  lambda-cd:
    name: Zip the code to be deployed to AWS Lambda
    runs-on: ubuntu-latest
    env:
      ZIP_FILE_NAME: package.zip
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Zip the code
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t ./
          zip -r ${{ env.ZIP_FILE_NAME }} ./*

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: deploy to AWS Lambda
        env:
          TEMPLATE_FILE: cloudformation/git_commit_count_bot.yml
          STACK_NAME: git-commit-count-bot-cfn
          LAMBDA_FUNCTION_NAME: git-commit-count-bot
        run: |
          aws cloudformation deploy \
            --template-file $TEMPLATE_FILE \
            --stack-name $STACK_NAME \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
            GitHubAccessToken=${{ secrets.ACCESS_TOKEN }} \
            SlackApiToken=${{ secrets.SLACK_API_TOKEN }}
          aws lambda update-function-code \
            --function-name $LAMBDA_FUNCTION_NAME \
            --zip-file fileb://${{ env.ZIP_FILE_NAME }} --publish
