name: deploy

on:
  push:
    branches:
      - master

jobs:
  lambda-cd:
    name: Zip the code to be deployed to AWS Lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Zip the code
        run: |
          pip3 install -r requirements.txt -t ./
          zip -r package.zip ./*

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: deploy to AWS Lambda
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/lambda.yml \
            --stack-name git-commit-count-bot-cfn
